version: 2.1
orbs:
  slim-xray-poc-orb: focaloid-dev/slim-xray-poc-orb@dev:021e6728d99623eb5c40b98479c318ec7a88fea6

jobs:
  scan:
    docker:
      - image: 'cimg/base:stable'
        auth:
          username: alshoja@gmail.com
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - slim-xray-poc-orb/scan:
          imageName: cimg/base:stable
workflows:
  slim-xray-poc-orb:
    jobs:
      - scan 