version: 2.1
orbs:
  slim-xray-poc-orb: focaloid-dev/slim-xray-poc-orb@dev:d2ae12b36a2a16be8fda9c29ca3221bdd03c804b

jobs:
  scan:
    docker:
      - image: 'cimg/base:stable'
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - slim-xray-poc-orb/scan:
          imageName: cimg/base:stable
      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file
workflows:
  slim-xray-poc-orb:
    jobs:
      - scan 
